###@SG.API_HostAddress = http://localhost:5203

###GET {{SG.API_HostAddress}}/weatherforecast/
###Accept: application/json

###

POST /connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=johndoe&password=A3ddj3wr